// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummonerInfo } from "./summoner";

export type FocusChange = {
  previous: number | null;
  requested: number | null;
  current: number | null;
};

export type LcuInstanceInfo = {
  pid: number;
  port: number;
  state: LcuInstanceState;
  isFocused: boolean;
  installDir: string | null;
  region: string | null;
  summoner: SummonerInfo | null;
  cmdArgs: LeagueClientCmdArgs;
};

export type LcuInstanceState = "idle" | "authenticating" | "ready" | "closing";

export type LeagueClientCmdArgs =
  | ({ family: "tencent" } & TencentLeagueClientCmdArgs)
  | ({ family: "riot" } & RiotLeagueClientCmdArgs);

export type RiotLeagueClientCmdArgs = {
  region: string | null;
  locale: string | null;
  "riotclient-auth-token": string | null;
  "riotclient-app-port": number | null;
  "remoting-auth-token": string | null;
  "app-port": number | null;
  "install-directory": string | null;
  "app-name": string | null;
  "ux-name": string | null;
  "ux-helper-name": string | null;
  "log-dir": string | null;
  "crash-reporting": string | null;
  "crash-environment": string | null;
  "app-log-file-path": string | null;
  "app-pid": number | null;
  "output-base-dir": string | null;
  "no-rads": boolean | null;
  "disable-self-update": boolean | null;
  "no-proxy-server": boolean | null;
  "ignore-certificate-errors": boolean | null;
  "riotgamesapi-standalone": boolean | null;
  "riotgamesapi-settings": string | null;
  "rga-lite": boolean | null;
  "respawn-command": string | null;
  "respawn-display-name": string | null;
};

export type TencentLeagueClientCmdArgs = {
  region: string | null;
  locale: string | null;
  rso_platform_id: string | null;
  "rso-auth.url": string | null;
  "rso-auth.client": string | null;
  "riotclient-auth-token": string | null;
  "riotclient-app-port": number | null;
  "remoting-auth-token": string | null;
  "app-port": number | null;
  "install-directory": string | null;
  "app-name": string | null;
  "ux-name": string | null;
  "ux-helper-name": string | null;
  "log-dir": string | null;
  "crash-reporting": string | null;
  "crash-environment": string | null;
  "app-log-file-path": string | null;
  "app-pid": number | null;
  "output-base-dir": string | null;
  "no-rads": boolean | null;
  "disable-self-update": boolean | null;
  "no-proxy-server": boolean | null;
  "ignore-certificate-errors": boolean | null;
  "riotclient-tencent": boolean | null;
  "t.lcdshost": string | null;
  "t.chathost": string | null;
  "t.storeurl": string | null;
  "t.rmsurl": string | null;
  "t.location": string | null;
  "tglog-endpoint": string | null;
  ccs: string | null;
  "entitlements-url": string | null;
  "dradis-endpoint": string | null;
  tDALauncher: boolean | null;
};
