// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpggBuildDto = {
  ids: Array<number>;
  play: number;
  pickRate: number;
  winRate: number;
};

export type OpggChampionDetailDto = {
  id: number;
  position: string;
  version: string;
  winRate: number;
  pickRate: number;
  banRate: number;
  tier: number;
  summonerSpells: Array<OpggBuildDto>;
  starterItems: Array<OpggBuildDto>;
  boots: Array<OpggBuildDto>;
  coreItems: Array<OpggBuildDto>;
  lastItems: Array<OpggBuildDto>;
  skillPriority: Array<string>;
  skillOrder: Array<string>;
  skillPickRate: number;
  skillWinRate: number;
  strongAgainst: Array<OpggCounterDto>;
  weakAgainst: Array<OpggCounterDto>;
};

export type OpggChampionListDto = {
  version: string;
  champions: Array<OpggChampionSummaryDto>;
};

export type OpggChampionSummaryDto = {
  id: number;
  winRate: number;
  pickRate: number;
  banRate: number;
  tier: number;
  positions: Array<OpggPositionSummaryDto>;
};

export type OpggCounterDto = {
  championId: number;
  play: number;
  winRate: number;
};

export type OpggPositionSummaryDto = {
  position: string;
  winRate: number;
  pickRate: number;
  roleRate: number;
};
